config/routes.rb
GroupVoting::Application.routes.draw do
  
  resources :logos

  resources :invites

  resources :memberships

  resources :user_groups

  authenticated :user do
    get 'welcome#index'=> 'welcome#index'
  end
  
  root :to => 'welcome#index'
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources  :users
  devise_for :models
  
 

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :user_group
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        format.json { render action: 'show', status: :created, location: @membership }
      else
        format.html { render action: 'new' }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:user_id, :user_group_id)
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :user_group_id %><br>
    <%= f.text_field :user_group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<h1>Listing memberships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>User group</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.user %></td>
        <td><%= membership.user_group %></td>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h1>New membership</h1>

<%= render 'form' %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @membership.user %>
</p>

<p>
  <strong>User group:</strong>
  <%= @membership.user_group %>
</p>

<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>