config/routes.rb
GroupVoting::Application.routes.draw do
  
  resources :logos

  resources :invites

  resources :memberships

  resources :user_groups

  authenticated :user do
    get 'welcome#index'=> 'welcome#index'
  end
  
  root :to => 'welcome#index'
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources  :users
  devise_for :models
  
 

end

app/models/logo.rb
class Logo < ActiveRecord::Base
end

app/controllers/logos_controller.rb
class LogosController < ApplicationController
  before_action :set_logo, only: [:show, :edit, :update, :destroy]
  acts_as_votable
  # GET /logos
  # GET /logos.json
  def index
    @logos = Logo.all
  end

  # GET /logos/1
  # GET /logos/1.json
  def show
  end

  # GET /logos/new
  def new
    @logo = Logo.new
  end

  # GET /logos/1/edit
  def edit
  end

  # POST /logos
  # POST /logos.json
  def create
    @logo = Logo.new(logo_params)

    respond_to do |format|
      if @logo.save
        format.html { redirect_to @logo, notice: 'Logo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @logo }
      else
        format.html { render action: 'new' }
        format.json { render json: @logo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logos/1
  # PATCH/PUT /logos/1.json
  def update
    respond_to do |format|
      if @logo.update(logo_params)
        format.html { redirect_to @logo, notice: 'Logo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @logo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logos/1
  # DELETE /logos/1.json
  def destroy
    @logo.destroy
    respond_to do |format|
      format.html { redirect_to logos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_logo
      @logo = Logo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def logo_params
      params.require(:logo).permit(:url, :user_group_id)
    end
end

app/helpers/logos_helper.rb
module LogosHelper
end

app/views/logos/_form.html.erb
<%= form_for(@logo) do |f| %>
  <% if @logo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@logo.errors.count, "error") %> prohibited this logo from being saved:</h2>

      <ul>
      <% @logo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :user_group_id %><br>
    <%= f.number_field :user_group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logos/edit.html.erb
<h1>Editing logo</h1>

<%= render 'form' %>

<%= link_to 'Show', @logo %> |
<%= link_to 'Back', logos_path %>

app/views/logos/index.html.erb
<h1>Listing logos</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>User group</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @logos.each do |logo| %>
      <tr>
        <td><%= logo.url %></td>
        <td><%= logo.user_group_id %></td>
        <td><%= link_to 'Show', logo %></td>
        <td><%= link_to 'Edit', edit_logo_path(logo) %></td>
        <td><%= link_to 'Destroy', logo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Logo', new_logo_path %>

app/views/logos/new.html.erb
<h1>New logo</h1>

<%= render 'form' %>

<%= link_to 'Back', logos_path %>

app/views/logos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @logo.url %>
</p>

<p>
  <strong>User group:</strong>
  <%= @logo.user_group_id %>
</p>

<%= link_to 'Edit', edit_logo_path(@logo) %> |
<%= link_to 'Back', logos_path %>